version: '3'

services:
  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reminder
    networks:
      - reminder-network

  reminder:
    container_name: reminder
    build:
      context: .
      dockerfile: Dockerfile
    image: reminder:latest
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - reminder-network
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/reminder"

networks:
  reminder-network:
    driver: bridge
